/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Pet Management API
 * Pet Management API with health logs, prescriptions, item master, and JWT authentication.
 * OpenAPI spec version: 1.5
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import axios from "axios";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  ListVisitsParams,
  ProblemDetail,
  Visit,
  VisitFields,
  VisitPage,
} from "../../types/api";

/**
 * @summary List visits with pagination (can filter by petId)
 */
export const listVisits = (
  params?: ListVisitsParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<VisitPage>> => {
  return axios.get(`/visits`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

export const getListVisitsQueryKey = (params?: ListVisitsParams) => {
  return [`/visits`, ...(params ? [params] : [])] as const;
};

export const getListVisitsQueryOptions = <
  TData = Awaited<ReturnType<typeof listVisits>>,
  TError = AxiosError<unknown>,
>(
  params?: ListVisitsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listVisits>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListVisitsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listVisits>>> = ({
    signal,
  }) => listVisits(params, { signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listVisits>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListVisitsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listVisits>>
>;
export type ListVisitsQueryError = AxiosError<unknown>;

export function useListVisits<
  TData = Awaited<ReturnType<typeof listVisits>>,
  TError = AxiosError<unknown>,
>(
  params: undefined | ListVisitsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listVisits>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listVisits>>,
          TError,
          Awaited<ReturnType<typeof listVisits>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListVisits<
  TData = Awaited<ReturnType<typeof listVisits>>,
  TError = AxiosError<unknown>,
>(
  params?: ListVisitsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listVisits>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listVisits>>,
          TError,
          Awaited<ReturnType<typeof listVisits>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListVisits<
  TData = Awaited<ReturnType<typeof listVisits>>,
  TError = AxiosError<unknown>,
>(
  params?: ListVisitsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listVisits>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List visits with pagination (can filter by petId)
 */

export function useListVisits<
  TData = Awaited<ReturnType<typeof listVisits>>,
  TError = AxiosError<unknown>,
>(
  params?: ListVisitsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listVisits>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListVisitsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Record a new visit
 */
export const addVisit = (
  visitFields: VisitFields,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<Visit>> => {
  return axios.post(`/visits`, visitFields, options);
};

export const getAddVisitMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addVisit>>,
    TError,
    { data: VisitFields },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof addVisit>>,
  TError,
  { data: VisitFields },
  TContext
> => {
  const mutationKey = ["addVisit"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addVisit>>,
    { data: VisitFields }
  > = (props) => {
    const { data } = props ?? {};

    return addVisit(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AddVisitMutationResult = NonNullable<
  Awaited<ReturnType<typeof addVisit>>
>;
export type AddVisitMutationBody = VisitFields;
export type AddVisitMutationError = AxiosError<unknown>;

/**
 * @summary Record a new visit
 */
export const useAddVisit = <TError = AxiosError<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof addVisit>>,
      TError,
      { data: VisitFields },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof addVisit>>,
  TError,
  { data: VisitFields },
  TContext
> => {
  const mutationOptions = getAddVisitMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const getVisit = (
  visitId: string,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<Visit>> => {
  return axios.get(`/visits/${visitId}`, options);
};

export const getGetVisitQueryKey = (visitId?: string) => {
  return [`/visits/${visitId}`] as const;
};

export const getGetVisitQueryOptions = <
  TData = Awaited<ReturnType<typeof getVisit>>,
  TError = AxiosError<ProblemDetail>,
>(
  visitId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getVisit>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetVisitQueryKey(visitId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getVisit>>> = ({
    signal,
  }) => getVisit(visitId, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!visitId,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getVisit>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetVisitQueryResult = NonNullable<
  Awaited<ReturnType<typeof getVisit>>
>;
export type GetVisitQueryError = AxiosError<ProblemDetail>;

export function useGetVisit<
  TData = Awaited<ReturnType<typeof getVisit>>,
  TError = AxiosError<ProblemDetail>,
>(
  visitId: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getVisit>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVisit>>,
          TError,
          Awaited<ReturnType<typeof getVisit>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetVisit<
  TData = Awaited<ReturnType<typeof getVisit>>,
  TError = AxiosError<ProblemDetail>,
>(
  visitId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getVisit>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVisit>>,
          TError,
          Awaited<ReturnType<typeof getVisit>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetVisit<
  TData = Awaited<ReturnType<typeof getVisit>>,
  TError = AxiosError<ProblemDetail>,
>(
  visitId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getVisit>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetVisit<
  TData = Awaited<ReturnType<typeof getVisit>>,
  TError = AxiosError<ProblemDetail>,
>(
  visitId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getVisit>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetVisitQueryOptions(visitId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const updateVisit = (
  visitId: string,
  visitFields: VisitFields,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<Visit>> => {
  return axios.put(`/visits/${visitId}`, visitFields, options);
};

export const getUpdateVisitMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateVisit>>,
    TError,
    { visitId: string; data: VisitFields },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateVisit>>,
  TError,
  { visitId: string; data: VisitFields },
  TContext
> => {
  const mutationKey = ["updateVisit"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateVisit>>,
    { visitId: string; data: VisitFields }
  > = (props) => {
    const { visitId, data } = props ?? {};

    return updateVisit(visitId, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateVisitMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateVisit>>
>;
export type UpdateVisitMutationBody = VisitFields;
export type UpdateVisitMutationError = AxiosError<unknown>;

export const useUpdateVisit = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateVisit>>,
      TError,
      { visitId: string; data: VisitFields },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateVisit>>,
  TError,
  { visitId: string; data: VisitFields },
  TContext
> => {
  const mutationOptions = getUpdateVisitMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const deleteVisit = (
  visitId: string,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
  return axios.delete(`/visits/${visitId}`, options);
};

export const getDeleteVisitMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteVisit>>,
    TError,
    { visitId: string },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteVisit>>,
  TError,
  { visitId: string },
  TContext
> => {
  const mutationKey = ["deleteVisit"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteVisit>>,
    { visitId: string }
  > = (props) => {
    const { visitId } = props ?? {};

    return deleteVisit(visitId, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteVisitMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteVisit>>
>;

export type DeleteVisitMutationError = AxiosError<unknown>;

export const useDeleteVisit = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteVisit>>,
      TError,
      { visitId: string },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteVisit>>,
  TError,
  { visitId: string },
  TContext
> => {
  const mutationOptions = getDeleteVisitMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
