/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Pet Management API
 * Pet Management API with health logs, prescriptions, and item master.
 * OpenAPI spec version: 1.2
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import axios from "axios";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";

import type { Clinic, ClinicFields, ProblemDetail } from "../../types/api";

/**
 * @summary List all clinics
 */
export const listClinics = (
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<Clinic[]>> => {
  return axios.get(`/clinics`, options);
};

export const getListClinicsQueryKey = () => {
  return [`/clinics`] as const;
};

export const getListClinicsQueryOptions = <
  TData = Awaited<ReturnType<typeof listClinics>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof listClinics>>, TError, TData>
  >;
  axios?: AxiosRequestConfig;
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListClinicsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listClinics>>> = ({
    signal,
  }) => listClinics({ signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listClinics>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListClinicsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listClinics>>
>;
export type ListClinicsQueryError = AxiosError<unknown>;

export function useListClinics<
  TData = Awaited<ReturnType<typeof listClinics>>,
  TError = AxiosError<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listClinics>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listClinics>>,
          TError,
          Awaited<ReturnType<typeof listClinics>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListClinics<
  TData = Awaited<ReturnType<typeof listClinics>>,
  TError = AxiosError<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listClinics>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listClinics>>,
          TError,
          Awaited<ReturnType<typeof listClinics>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListClinics<
  TData = Awaited<ReturnType<typeof listClinics>>,
  TError = AxiosError<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listClinics>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List all clinics
 */

export function useListClinics<
  TData = Awaited<ReturnType<typeof listClinics>>,
  TError = AxiosError<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listClinics>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListClinicsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Add a new clinic
 */
export const addClinic = (
  clinicFields: ClinicFields,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<Clinic>> => {
  return axios.post(`/clinics`, clinicFields, options);
};

export const getAddClinicMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addClinic>>,
    TError,
    { data: ClinicFields },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof addClinic>>,
  TError,
  { data: ClinicFields },
  TContext
> => {
  const mutationKey = ["addClinic"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addClinic>>,
    { data: ClinicFields }
  > = (props) => {
    const { data } = props ?? {};

    return addClinic(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AddClinicMutationResult = NonNullable<
  Awaited<ReturnType<typeof addClinic>>
>;
export type AddClinicMutationBody = ClinicFields;
export type AddClinicMutationError = AxiosError<unknown>;

/**
 * @summary Add a new clinic
 */
export const useAddClinic = <TError = AxiosError<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof addClinic>>,
      TError,
      { data: ClinicFields },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof addClinic>>,
  TError,
  { data: ClinicFields },
  TContext
> => {
  const mutationOptions = getAddClinicMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const getClinic = (
  clinicId: string,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<Clinic>> => {
  return axios.get(`/clinics/${clinicId}`, options);
};

export const getGetClinicQueryKey = (clinicId?: string) => {
  return [`/clinics/${clinicId}`] as const;
};

export const getGetClinicQueryOptions = <
  TData = Awaited<ReturnType<typeof getClinic>>,
  TError = AxiosError<ProblemDetail>,
>(
  clinicId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getClinic>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetClinicQueryKey(clinicId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getClinic>>> = ({
    signal,
  }) => getClinic(clinicId, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!clinicId,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getClinic>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetClinicQueryResult = NonNullable<
  Awaited<ReturnType<typeof getClinic>>
>;
export type GetClinicQueryError = AxiosError<ProblemDetail>;

export function useGetClinic<
  TData = Awaited<ReturnType<typeof getClinic>>,
  TError = AxiosError<ProblemDetail>,
>(
  clinicId: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getClinic>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getClinic>>,
          TError,
          Awaited<ReturnType<typeof getClinic>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetClinic<
  TData = Awaited<ReturnType<typeof getClinic>>,
  TError = AxiosError<ProblemDetail>,
>(
  clinicId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getClinic>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getClinic>>,
          TError,
          Awaited<ReturnType<typeof getClinic>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetClinic<
  TData = Awaited<ReturnType<typeof getClinic>>,
  TError = AxiosError<ProblemDetail>,
>(
  clinicId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getClinic>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetClinic<
  TData = Awaited<ReturnType<typeof getClinic>>,
  TError = AxiosError<ProblemDetail>,
>(
  clinicId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getClinic>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetClinicQueryOptions(clinicId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const updateClinic = (
  clinicId: string,
  clinicFields: ClinicFields,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<Clinic>> => {
  return axios.put(`/clinics/${clinicId}`, clinicFields, options);
};

export const getUpdateClinicMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateClinic>>,
    TError,
    { clinicId: string; data: ClinicFields },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateClinic>>,
  TError,
  { clinicId: string; data: ClinicFields },
  TContext
> => {
  const mutationKey = ["updateClinic"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateClinic>>,
    { clinicId: string; data: ClinicFields }
  > = (props) => {
    const { clinicId, data } = props ?? {};

    return updateClinic(clinicId, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateClinicMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateClinic>>
>;
export type UpdateClinicMutationBody = ClinicFields;
export type UpdateClinicMutationError = AxiosError<unknown>;

export const useUpdateClinic = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateClinic>>,
      TError,
      { clinicId: string; data: ClinicFields },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateClinic>>,
  TError,
  { clinicId: string; data: ClinicFields },
  TContext
> => {
  const mutationOptions = getUpdateClinicMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const deleteClinic = (
  clinicId: string,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
  return axios.delete(`/clinics/${clinicId}`, options);
};

export const getDeleteClinicMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteClinic>>,
    TError,
    { clinicId: string },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteClinic>>,
  TError,
  { clinicId: string },
  TContext
> => {
  const mutationKey = ["deleteClinic"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteClinic>>,
    { clinicId: string }
  > = (props) => {
    const { clinicId } = props ?? {};

    return deleteClinic(clinicId, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteClinicMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteClinic>>
>;

export type DeleteClinicMutationError = AxiosError<unknown>;

export const useDeleteClinic = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteClinic>>,
      TError,
      { clinicId: string },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteClinic>>,
  TError,
  { clinicId: string },
  TContext
> => {
  const mutationOptions = getDeleteClinicMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
