/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Pet Management API
 * Pet Management API with health logs, prescriptions, item master, and JWT authentication.
 * OpenAPI spec version: 1.5
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import axios from "axios";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  ListPrescriptionsParams,
  Prescription,
  PrescriptionFields,
  PrescriptionPage,
} from "../../types/api";

/**
 * @summary List prescription master data with pagination
 */
export const listPrescriptions = (
  params?: ListPrescriptionsParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<PrescriptionPage>> => {
  return axios.get(`/prescriptions`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

export const getListPrescriptionsQueryKey = (
  params?: ListPrescriptionsParams,
) => {
  return [`/prescriptions`, ...(params ? [params] : [])] as const;
};

export const getListPrescriptionsQueryOptions = <
  TData = Awaited<ReturnType<typeof listPrescriptions>>,
  TError = AxiosError<unknown>,
>(
  params?: ListPrescriptionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listPrescriptions>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getListPrescriptionsQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listPrescriptions>>
  > = ({ signal }) => listPrescriptions(params, { signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listPrescriptions>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListPrescriptionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listPrescriptions>>
>;
export type ListPrescriptionsQueryError = AxiosError<unknown>;

export function useListPrescriptions<
  TData = Awaited<ReturnType<typeof listPrescriptions>>,
  TError = AxiosError<unknown>,
>(
  params: undefined | ListPrescriptionsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listPrescriptions>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPrescriptions>>,
          TError,
          Awaited<ReturnType<typeof listPrescriptions>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListPrescriptions<
  TData = Awaited<ReturnType<typeof listPrescriptions>>,
  TError = AxiosError<unknown>,
>(
  params?: ListPrescriptionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listPrescriptions>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPrescriptions>>,
          TError,
          Awaited<ReturnType<typeof listPrescriptions>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListPrescriptions<
  TData = Awaited<ReturnType<typeof listPrescriptions>>,
  TError = AxiosError<unknown>,
>(
  params?: ListPrescriptionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listPrescriptions>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List prescription master data with pagination
 */

export function useListPrescriptions<
  TData = Awaited<ReturnType<typeof listPrescriptions>>,
  TError = AxiosError<unknown>,
>(
  params?: ListPrescriptionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listPrescriptions>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListPrescriptionsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Add new prescription master data
 */
export const addPrescription = (
  prescriptionFields: PrescriptionFields,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<Prescription>> => {
  return axios.post(`/prescriptions`, prescriptionFields, options);
};

export const getAddPrescriptionMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addPrescription>>,
    TError,
    { data: PrescriptionFields },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof addPrescription>>,
  TError,
  { data: PrescriptionFields },
  TContext
> => {
  const mutationKey = ["addPrescription"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addPrescription>>,
    { data: PrescriptionFields }
  > = (props) => {
    const { data } = props ?? {};

    return addPrescription(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AddPrescriptionMutationResult = NonNullable<
  Awaited<ReturnType<typeof addPrescription>>
>;
export type AddPrescriptionMutationBody = PrescriptionFields;
export type AddPrescriptionMutationError = AxiosError<unknown>;

/**
 * @summary Add new prescription master data
 */
export const useAddPrescription = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof addPrescription>>,
      TError,
      { data: PrescriptionFields },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof addPrescription>>,
  TError,
  { data: PrescriptionFields },
  TContext
> => {
  const mutationOptions = getAddPrescriptionMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
