/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Pet Management API
 * Pet Management API with health logs, prescriptions, and item master.
 * OpenAPI spec version: 1.4
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import axios from "axios";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  Item,
  ItemFields,
  ItemPage,
  ListItemsParams,
} from "../../types/api";

/**
 * @summary List item master data with pagination
 */
export const listItems = (
  params?: ListItemsParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ItemPage>> => {
  return axios.get(`/items`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

export const getListItemsQueryKey = (params?: ListItemsParams) => {
  return [`/items`, ...(params ? [params] : [])] as const;
};

export const getListItemsQueryOptions = <
  TData = Awaited<ReturnType<typeof listItems>>,
  TError = AxiosError<unknown>,
>(
  params?: ListItemsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listItems>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListItemsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listItems>>> = ({
    signal,
  }) => listItems(params, { signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listItems>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListItemsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listItems>>
>;
export type ListItemsQueryError = AxiosError<unknown>;

export function useListItems<
  TData = Awaited<ReturnType<typeof listItems>>,
  TError = AxiosError<unknown>,
>(
  params: undefined | ListItemsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listItems>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listItems>>,
          TError,
          Awaited<ReturnType<typeof listItems>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListItems<
  TData = Awaited<ReturnType<typeof listItems>>,
  TError = AxiosError<unknown>,
>(
  params?: ListItemsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listItems>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listItems>>,
          TError,
          Awaited<ReturnType<typeof listItems>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListItems<
  TData = Awaited<ReturnType<typeof listItems>>,
  TError = AxiosError<unknown>,
>(
  params?: ListItemsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listItems>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List item master data with pagination
 */

export function useListItems<
  TData = Awaited<ReturnType<typeof listItems>>,
  TError = AxiosError<unknown>,
>(
  params?: ListItemsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listItems>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListItemsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Add new item master data
 */
export const addItem = (
  itemFields: ItemFields,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<Item>> => {
  return axios.post(`/items`, itemFields, options);
};

export const getAddItemMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addItem>>,
    TError,
    { data: ItemFields },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof addItem>>,
  TError,
  { data: ItemFields },
  TContext
> => {
  const mutationKey = ["addItem"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addItem>>,
    { data: ItemFields }
  > = (props) => {
    const { data } = props ?? {};

    return addItem(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AddItemMutationResult = NonNullable<
  Awaited<ReturnType<typeof addItem>>
>;
export type AddItemMutationBody = ItemFields;
export type AddItemMutationError = AxiosError<unknown>;

/**
 * @summary Add new item master data
 */
export const useAddItem = <TError = AxiosError<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof addItem>>,
      TError,
      { data: ItemFields },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof addItem>>,
  TError,
  { data: ItemFields },
  TContext
> => {
  const mutationOptions = getAddItemMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
