/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Pet Management API
 * Pet Management API with health logs, prescriptions, and item master.
 * OpenAPI spec version: 1.2
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import axios from "axios";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  VisitPrescription,
  VisitPrescriptionFields,
} from "../../types/api";

/**
 * @summary List prescriptions for a specific visit
 */
export const listVisitPrescriptions = (
  visitId: string,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<VisitPrescription[]>> => {
  return axios.get(`/visits/${visitId}/prescriptions`, options);
};

export const getListVisitPrescriptionsQueryKey = (visitId?: string) => {
  return [`/visits/${visitId}/prescriptions`] as const;
};

export const getListVisitPrescriptionsQueryOptions = <
  TData = Awaited<ReturnType<typeof listVisitPrescriptions>>,
  TError = AxiosError<unknown>,
>(
  visitId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listVisitPrescriptions>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getListVisitPrescriptionsQueryKey(visitId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listVisitPrescriptions>>
  > = ({ signal }) =>
    listVisitPrescriptions(visitId, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!visitId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof listVisitPrescriptions>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListVisitPrescriptionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listVisitPrescriptions>>
>;
export type ListVisitPrescriptionsQueryError = AxiosError<unknown>;

export function useListVisitPrescriptions<
  TData = Awaited<ReturnType<typeof listVisitPrescriptions>>,
  TError = AxiosError<unknown>,
>(
  visitId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listVisitPrescriptions>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listVisitPrescriptions>>,
          TError,
          Awaited<ReturnType<typeof listVisitPrescriptions>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListVisitPrescriptions<
  TData = Awaited<ReturnType<typeof listVisitPrescriptions>>,
  TError = AxiosError<unknown>,
>(
  visitId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listVisitPrescriptions>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listVisitPrescriptions>>,
          TError,
          Awaited<ReturnType<typeof listVisitPrescriptions>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListVisitPrescriptions<
  TData = Awaited<ReturnType<typeof listVisitPrescriptions>>,
  TError = AxiosError<unknown>,
>(
  visitId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listVisitPrescriptions>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List prescriptions for a specific visit
 */

export function useListVisitPrescriptions<
  TData = Awaited<ReturnType<typeof listVisitPrescriptions>>,
  TError = AxiosError<unknown>,
>(
  visitId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listVisitPrescriptions>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListVisitPrescriptionsQueryOptions(visitId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Add a prescription to a visit
 */
export const addVisitPrescription = (
  visitId: string,
  visitPrescriptionFields: VisitPrescriptionFields,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<VisitPrescription>> => {
  return axios.post(
    `/visits/${visitId}/prescriptions`,
    visitPrescriptionFields,
    options,
  );
};

export const getAddVisitPrescriptionMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addVisitPrescription>>,
    TError,
    { visitId: string; data: VisitPrescriptionFields },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof addVisitPrescription>>,
  TError,
  { visitId: string; data: VisitPrescriptionFields },
  TContext
> => {
  const mutationKey = ["addVisitPrescription"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addVisitPrescription>>,
    { visitId: string; data: VisitPrescriptionFields }
  > = (props) => {
    const { visitId, data } = props ?? {};

    return addVisitPrescription(visitId, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AddVisitPrescriptionMutationResult = NonNullable<
  Awaited<ReturnType<typeof addVisitPrescription>>
>;
export type AddVisitPrescriptionMutationBody = VisitPrescriptionFields;
export type AddVisitPrescriptionMutationError = AxiosError<unknown>;

/**
 * @summary Add a prescription to a visit
 */
export const useAddVisitPrescription = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof addVisitPrescription>>,
      TError,
      { visitId: string; data: VisitPrescriptionFields },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof addVisitPrescription>>,
  TError,
  { visitId: string; data: VisitPrescriptionFields },
  TContext
> => {
  const mutationOptions = getAddVisitPrescriptionMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Remove a prescription from a visit
 */
export const deleteVisitPrescription = (
  visitId: string,
  visitPrescriptionId: string,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
  return axios.delete(
    `/visits/${visitId}/prescriptions/${visitPrescriptionId}`,
    options,
  );
};

export const getDeleteVisitPrescriptionMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteVisitPrescription>>,
    TError,
    { visitId: string; visitPrescriptionId: string },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteVisitPrescription>>,
  TError,
  { visitId: string; visitPrescriptionId: string },
  TContext
> => {
  const mutationKey = ["deleteVisitPrescription"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteVisitPrescription>>,
    { visitId: string; visitPrescriptionId: string }
  > = (props) => {
    const { visitId, visitPrescriptionId } = props ?? {};

    return deleteVisitPrescription(visitId, visitPrescriptionId, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteVisitPrescriptionMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteVisitPrescription>>
>;

export type DeleteVisitPrescriptionMutationError = AxiosError<unknown>;

/**
 * @summary Remove a prescription from a visit
 */
export const useDeleteVisitPrescription = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteVisitPrescription>>,
      TError,
      { visitId: string; visitPrescriptionId: string },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteVisitPrescription>>,
  TError,
  { visitId: string; visitPrescriptionId: string },
  TContext
> => {
  const mutationOptions = getDeleteVisitPrescriptionMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
