/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Pet Management API
 * Pet Management API with health logs, prescriptions, and item master.
 * OpenAPI spec version: 1.4
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import axios from "axios";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";

import type { ProblemDetail } from "../../types/api";

/**
 * Produces sample error response.
 * @summary Always fails
 */
export const failingRequest = (
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<unknown>> => {
  return axios.get(`/oops`, options);
};

export const getFailingRequestQueryKey = () => {
  return [`/oops`] as const;
};

export const getFailingRequestQueryOptions = <
  TData = Awaited<ReturnType<typeof failingRequest>>,
  TError = AxiosError<ProblemDetail>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof failingRequest>>, TError, TData>
  >;
  axios?: AxiosRequestConfig;
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFailingRequestQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof failingRequest>>> = ({
    signal,
  }) => failingRequest({ signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof failingRequest>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FailingRequestQueryResult = NonNullable<
  Awaited<ReturnType<typeof failingRequest>>
>;
export type FailingRequestQueryError = AxiosError<ProblemDetail>;

export function useFailingRequest<
  TData = Awaited<ReturnType<typeof failingRequest>>,
  TError = AxiosError<ProblemDetail>,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof failingRequest>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof failingRequest>>,
          TError,
          Awaited<ReturnType<typeof failingRequest>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFailingRequest<
  TData = Awaited<ReturnType<typeof failingRequest>>,
  TError = AxiosError<ProblemDetail>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof failingRequest>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof failingRequest>>,
          TError,
          Awaited<ReturnType<typeof failingRequest>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFailingRequest<
  TData = Awaited<ReturnType<typeof failingRequest>>,
  TError = AxiosError<ProblemDetail>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof failingRequest>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Always fails
 */

export function useFailingRequest<
  TData = Awaited<ReturnType<typeof failingRequest>>,
  TError = AxiosError<ProblemDetail>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof failingRequest>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getFailingRequestQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
