/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Pet Management API
 * Pet Management API with health logs, prescriptions, and item master.
 * OpenAPI spec version: 1.2
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import axios from "axios";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";

import type { PetType, PetTypeFields } from "../../types/api";

export const listPetTypes = (
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<PetType[]>> => {
  return axios.get(`/pettypes`, options);
};

export const getListPetTypesQueryKey = () => {
  return [`/pettypes`] as const;
};

export const getListPetTypesQueryOptions = <
  TData = Awaited<ReturnType<typeof listPetTypes>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof listPetTypes>>, TError, TData>
  >;
  axios?: AxiosRequestConfig;
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListPetTypesQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listPetTypes>>> = ({
    signal,
  }) => listPetTypes({ signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listPetTypes>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListPetTypesQueryResult = NonNullable<
  Awaited<ReturnType<typeof listPetTypes>>
>;
export type ListPetTypesQueryError = AxiosError<unknown>;

export function useListPetTypes<
  TData = Awaited<ReturnType<typeof listPetTypes>>,
  TError = AxiosError<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listPetTypes>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPetTypes>>,
          TError,
          Awaited<ReturnType<typeof listPetTypes>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListPetTypes<
  TData = Awaited<ReturnType<typeof listPetTypes>>,
  TError = AxiosError<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listPetTypes>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPetTypes>>,
          TError,
          Awaited<ReturnType<typeof listPetTypes>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListPetTypes<
  TData = Awaited<ReturnType<typeof listPetTypes>>,
  TError = AxiosError<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listPetTypes>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useListPetTypes<
  TData = Awaited<ReturnType<typeof listPetTypes>>,
  TError = AxiosError<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listPetTypes>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListPetTypesQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const addPetType = (
  petTypeFields: PetTypeFields,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<PetType>> => {
  return axios.post(`/pettypes`, petTypeFields, options);
};

export const getAddPetTypeMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addPetType>>,
    TError,
    { data: PetTypeFields },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof addPetType>>,
  TError,
  { data: PetTypeFields },
  TContext
> => {
  const mutationKey = ["addPetType"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addPetType>>,
    { data: PetTypeFields }
  > = (props) => {
    const { data } = props ?? {};

    return addPetType(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AddPetTypeMutationResult = NonNullable<
  Awaited<ReturnType<typeof addPetType>>
>;
export type AddPetTypeMutationBody = PetTypeFields;
export type AddPetTypeMutationError = AxiosError<unknown>;

export const useAddPetType = <TError = AxiosError<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof addPetType>>,
      TError,
      { data: PetTypeFields },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof addPetType>>,
  TError,
  { data: PetTypeFields },
  TContext
> => {
  const mutationOptions = getAddPetTypeMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
