/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Pet Management API
 * Pet Management API with health logs, prescriptions, item master, and JWT authentication.
 * OpenAPI spec version: 1.5
 */
import type { UserBase } from "./userBase";
import type { AdminUserUpdateAllOf } from "./adminUserUpdateAllOf";

export type AdminUserUpdate = UserBase & AdminUserUpdateAllOf;
