/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Pet Management API
 * Pet Management API with health logs, prescriptions, item master, and JWT authentication.
 * OpenAPI spec version: 2
 */
import type { PageMetadata } from "./pageMetadata";
import type { ClinicPageAllOf } from "./clinicPageAllOf";

export type ClinicPage = PageMetadata & ClinicPageAllOf;
