/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Pet Management API
 * Pet Management API with health logs, prescriptions, item master, and JWT authentication.
 * OpenAPI spec version: 2
 */
import type { DocumentFields } from "./documentFields";
import type { DocumentAllOf } from "./documentAllOf";

export type Document = DocumentFields & DocumentAllOf;
