/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Pet Management API
 * Pet Management API with health logs, prescriptions, item master, and JWT authentication.
 * OpenAPI spec version: 2
 */
import type { DocumentUpdateFieldsBody } from "./documentUpdateFieldsBody";

export interface DocumentUpdateFields {
  title?: string;
  /** JSONB body for block-based structure */
  body?: DocumentUpdateFieldsBody;
}
