/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Pet Management API
 * Pet Management API with health logs, prescriptions, item master, and JWT authentication.
 * OpenAPI spec version: 1.5
 */

export type ItemCategory = (typeof ItemCategory)[keyof typeof ItemCategory];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ItemCategory = {
  food: "food",
  treat: "treat",
  supplement: "supplement",
  pad: "pad",
  toy: "toy",
  collar: "collar",
  hygiene: "hygiene",
  medical: "medical",
  other: "other",
} as const;
