/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Pet Management API
 * Pet Management API with health logs, prescriptions, and item master.
 * OpenAPI spec version: 1.2
 */
import type { ItemCategory } from "./itemCategory";
import type { ItemFieldsMetadata } from "./itemFieldsMetadata";

export interface ItemFields {
  name: string;
  category: ItemCategory;
  note?: string;
  /** JSONB metadata for external links or details */
  metadata?: ItemFieldsMetadata;
}
