/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Pet Management API
 * Pet Management API with health logs, prescriptions, item master, and JWT authentication.
 * OpenAPI spec version: 1.5
 */

/**
 * JSONB metadata for external links or details
 */
export type ItemFieldsMetadata = { [key: string]: unknown };
