/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Pet Management API
 * Pet Management API with health logs, prescriptions, item master, and JWT authentication.
 * OpenAPI spec version: 1.5
 */

export interface JwtResponse {
  accessToken: string;
  tokenType: string;
  refreshToken: string;
  expiresIn?: number;
  userId: string;
}
