/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Pet Management API
 * Pet Management API with health logs, prescriptions, item master, and JWT authentication.
 * OpenAPI spec version: 2
 */
import type { PetFields } from "./petFields";
import type { PetAllOf } from "./petAllOf";

export type Pet = PetFields & PetAllOf;
