/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Pet Management API
 * Pet Management API with health logs, prescriptions, and item master.
 * OpenAPI spec version: 1.4
 */

export type PetAllOf = {
  readonly id: string;
  readonly createdAt: string;
  readonly updatedAt: string;
};
