/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Pet Management API
 * Pet Management API with health logs, prescriptions, item master, and JWT authentication.
 * OpenAPI spec version: 2
 */

export type PetAllOf = {
  /** The owner ID */
  readonly userId?: string;
  readonly id: string;
  /** URL of pet icon image */
  icon?: string;
  readonly createdAt: string;
  readonly updatedAt: string;
};
