/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Pet Management API
 * Pet Management API with health logs, prescriptions, and item master.
 * OpenAPI spec version: 1.2
 */

export interface PetFields {
  /** @maxLength 30 */
  name: string;
  birthDate?: string;
  /** @maxLength 10 */
  sex?: string;
  typeId: string;
  /** The owner ID */
  userId: string;
}
