/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Pet Management API
 * Pet Management API with health logs, prescriptions, item master, and JWT authentication.
 * OpenAPI spec version: 2
 */

export type PetSex = (typeof PetSex)[keyof typeof PetSex];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PetSex = {
  male: "male",
  female: "female",
  unknown: "unknown",
} as const;
