/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Pet Management API
 * Pet Management API with health logs, prescriptions, item master, and JWT authentication.
 * OpenAPI spec version: 2
 */
import type { PrescriptionFields } from "./prescriptionFields";
import type { PrescriptionAllOf } from "./prescriptionAllOf";

export type Prescription = PrescriptionFields & PrescriptionAllOf;
