/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Pet Management API
 * Pet Management API with health logs, prescriptions, and item master.
 * OpenAPI spec version: 1.2
 */

export type PrescriptionCategory =
  (typeof PrescriptionCategory)[keyof typeof PrescriptionCategory];

 
export const PrescriptionCategory = {
  vaccine: "vaccine",
  heartworm: "heartworm",
  flea_tick: "flea_tick",
  other: "other",
} as const;
