/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Pet Management API
 * Pet Management API with health logs, prescriptions, item master, and JWT authentication.
 * OpenAPI spec version: 2
 */

export type PrescriptionCategory =
  (typeof PrescriptionCategory)[keyof typeof PrescriptionCategory];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PrescriptionCategory = {
  vaccine: "vaccine",
  heartworm: "heartworm",
  flea_tick: "flea_tick",
  other: "other",
} as const;
