/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Pet Management API
 * Pet Management API with health logs, prescriptions, item master, and JWT authentication.
 * OpenAPI spec version: 1.5
 */
import type { PrescriptionCategory } from "./prescriptionCategory";

export interface PrescriptionFields {
  category: PrescriptionCategory;
  name: string;
  /** Tablet, Injection, Spot-on, etc. */
  form?: string;
  strength?: string;
  note?: string;
}
