/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Pet Management API
 * Pet Management API with health logs, prescriptions, and item master.
 * OpenAPI spec version: 1.4
 */

export type RoleName = (typeof RoleName)[keyof typeof RoleName];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RoleName = {
  owner: "owner",
  vet: "vet",
  nurse: "nurse",
  receptionist: "receptionist",
  clinic_admin: "clinic_admin",
  admin: "admin",
} as const;
