/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Pet Management API
 * Pet Management API with health logs, prescriptions, item master, and JWT authentication.
 * OpenAPI spec version: 1.5
 */

export interface SignupRequest {
  /** @maxLength 255 */
  email: string;
  /**
   * @minLength 8
   * @maxLength 128
   * @pattern ^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).+$
   */
  password: string;
}
