/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Pet Management API
 * Pet Management API with health logs, prescriptions, and item master.
 * OpenAPI spec version: 1.4
 */

/**
 * The size of the page to be returned
 */
export type SizeParamParameter = number;
