/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Pet Management API
 * Pet Management API with health logs, prescriptions, item master, and JWT authentication.
 * OpenAPI spec version: 2
 */

export interface UserItemFields {
  /** The user ID */
  userId: string;
  /** The item ID */
  itemId: string;
  /** User's note for the item */
  note?: string;
  /** When the item was recorded by the user */
  recordedAt?: string;
}
