/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Pet Management API
 * Pet Management API with health logs, prescriptions, and item master.
 * OpenAPI spec version: 1.4
 */
import type { Role } from "./role";

export type UserResponseAllOf = {
  id: string;
  roles: Role[];
  enabled: boolean;
  createdAt: string;
  updatedAt: string;
};
