/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Pet Management API
 * Pet Management API with health logs, prescriptions, item master, and JWT authentication.
 * OpenAPI spec version: 2
 */

export interface UserBase {
  /**
   * @minLength 1
   * @maxLength 20
   */
  username: string;
  /** @maxLength 50 */
  firstName?: string;
  /** @maxLength 50 */
  lastName?: string;
  /**
   * @maxLength 50
   * @pattern ^[ァ-ヶー]*$
   */
  firstNameKana?: string;
  /**
   * @maxLength 50
   * @pattern ^[ァ-ヶー]*$
   */
  lastNameKana?: string;
  /** @maxLength 255 */
  email: string;
  /**
   * @maxLength 8
   * @pattern ^$|^\d{3}-?\d{4}$
   */
  postalCode?: string;
  /** @maxLength 10 */
  prefecture?: string;
  /** @maxLength 80 */
  city?: string;
  /** @maxLength 255 */
  address?: string;
  /**
   * @maxLength 20
   * @pattern ^$|^[0-9-]*$
   */
  telephone?: string;
}
