/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Pet Management API
 * Pet Management API with health logs, prescriptions, and item master.
 * OpenAPI spec version: 1.2
 */
import type { UserFields } from "./userFields";
import type { UserAllOf } from "./userAllOf";

export type User = UserFields & UserAllOf;
