/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Pet Management API
 * Pet Management API with health logs, prescriptions, and item master.
 * OpenAPI spec version: 1.4
 */

export interface UserBase {
  /**
   * @minLength 1
   * @maxLength 20
   */
  username: string;
  firstName: string;
  lastName: string;
  firstNameKana: string;
  lastNameKana: string;
  email: string;
  /** @maxLength 8 */
  postalCode?: string;
  prefecture?: string;
  /** @maxLength 80 */
  city?: string;
  /** @maxLength 255 */
  address?: string;
  /**
   * @maxLength 20
   * @pattern ^[0-9-]*$
   */
  telephone?: string;
}
