/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Pet Management API
 * Pet Management API with health logs, prescriptions, and item master.
 * OpenAPI spec version: 1.2
 */

export interface UserFields {
  /**
   * @minLength 1
   * @maxLength 20
   */
  username: string;
  /** @maxLength 255 */
  password: string;
  enabled?: boolean;
  firstName: string;
  lastName: string;
  firstNameKana: string;
  lastNameKana: string;
  email: string;
  /** @maxLength 8 */
  postalCode?: string;
  prefecture?: string;
  /** @maxLength 80 */
  city?: string;
  /** @maxLength 255 */
  address?: string;
  /**
   * @maxLength 20
   * @pattern ^[0-9-]*$
   */
  telephone?: string;
  /** @maxLength 20 */
  role?: string;
}
