/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Pet Management API
 * Pet Management API with health logs, prescriptions, item master, and JWT authentication.
 * OpenAPI spec version: 1.5
 */
import type { PageMetadata } from "./pageMetadata";
import type { UserPageAllOf } from "./userPageAllOf";

export type UserPage = PageMetadata & UserPageAllOf;
