/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Pet Management API
 * Pet Management API with health logs, prescriptions, item master, and JWT authentication.
 * OpenAPI spec version: 2
 */
import type { UserBase } from "./userBase";
import type { UserResponseAllOf } from "./userResponseAllOf";

export type UserResponse = UserBase & UserResponseAllOf;
