/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Pet Management API
 * Pet Management API with health logs, prescriptions, and item master.
 * OpenAPI spec version: 1.2
 */

export type VisitType = (typeof VisitType)[keyof typeof VisitType];

 
export const VisitType = {
  vaccine: "vaccine",
  heartworm: "heartworm",
  flea_tick: "flea_tick",
  checkup: "checkup",
  general: "general",
} as const;
