/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Pet Management API
 * Pet Management API with health logs, prescriptions, item master, and JWT authentication.
 * OpenAPI spec version: 2
 */
import type { VisitType } from "./visitType";
import type { Currency } from "./currency";

export interface VisitFields {
  petId: string;
  clinicId: string;
  visitedOn: string;
  /** Weight in kg */
  weight?: number;
  visitType?: VisitType;
  reason?: string;
  diagnosis?: string;
  treatment?: string;
  nextDueOn?: string;
  totalFee?: number;
  currency?: Currency;
  note?: string;
}
