/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Pet Management API
 * Pet Management API with health logs, prescriptions, and item master.
 * OpenAPI spec version: 1.2
 */
import type { VisitType } from "./visitType";

export interface VisitFields {
  userId: string;
  petId: string;
  clinicId: string;
  visitedOn: string;
  /** Weight in kg */
  weight?: number;
  visitType?: VisitType;
  reason?: string;
  diagnosis?: string;
  treatment?: string;
  nextDueOn?: string;
  totalFee?: number;
  /** @pattern ^[A-Z]{3}$ */
  currency?: string;
  note?: string;
}
