/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Pet Management API
 * Pet Management API with health logs, prescriptions, item master, and JWT authentication.
 * OpenAPI spec version: 2
 */

export interface VisitPrescriptionFields {
  visitId: string;
  prescriptionId: string;
  /**
   * Quantity (e.g., 1.5)
   * @minimum 0
   * @exclusiveMinimum
   */
  quantity: number;
  unit: string;
  /** @minimum 1 */
  days?: number;
  dosageInstructions?: string;
  purpose?: string;
}
